[package]
name = "minirng"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "A mini audio library"
repository = "https://github.com/ThePJB/minirng"

[dependencies]
minvect = "0.1.6"

[dev-dependencies]
minimg = "0.1.4"

[profile.test]
opt-level = 3
